[master]
k8s-master ansible_host=167.234.247.229 ansible_user=opc ansible_ssh_private_key_file=/home/gabriel/.ssh/id_ed25519

[workers]
k8s-worker-1 ansible_host=137.131.250.223 ansible_user=opc ansible_ssh_private_key_file=/home/gabriel/.ssh/id_ed25519
k8s-worker-2 ansible_host=137.131.202.111 ansible_user=opc ansible_ssh_private_key_file=/home/gabriel/.ssh/id_ed25519

[k8s_cluster:children]
master
workers